#!/bin/bash

DATETIME=`date '+%Y-%m-%d %H:%M'`
echo ''
echo "# RexReplace vs `sed` speed test"
echo $DATETIME
echo ''

echo "This test will remove HTML tags from the HTML sorce of George Orwell's 1984 to get the pure text version."

echo "All test results printed are the sum of 10 rounds given in seconds."

TIMEFORMAT=%R

create_testdata(){
	#return # for debug

	curl -s 1984.surge.sh > source.file
	head -c $((1*1024))  source.file > 1Kb.file
	head -c $((5*1024))  source.file > 5Kb.file
	head -c $((10*1024)) source.file > 10Kb.file
	head -c $((100*1024)) source.file > 100Kb.file
	head -c $((500*1024)) source.file > 500Kb.file
	echo '' > 1Mb.file; for i in {1..2}; do cat 500Kb.file >> 1Mb.file; done
	echo '' > 5Mb.file; for i in {1..5}; do cat 1Mb.file >> 5Mb.file; done
	echo '' > 10Mb.file; for i in {1..10}; do cat 1Mb.file >> 10Mb.file; done
	echo '' > 25Mb.file; for i in {1..25}; do cat 1Mb.file >> 25Mb.file; done
	echo '' > 50Mb.file; for i in {1..50}; do cat 1Mb.file >> 50Mb.file; done
	echo '' > 100Mb.file; for i in {1..100}; do cat 1Mb.file >> 100Mb.file; done
}

remove_testdata(){
	#return # for debug

	rm source.file
	rm 1Kb.file
	rm 5Kb.file
	rm 10Kb.file
	rm 100Kb.file
	rm 500Kb.file
	rm 1Mb.file
	rm 5Mb.file
	rm 10Mb.file
	rm 25Mb.file
	rm 50Mb.file
	rm 100Mb.file

	rm A0.txt
	rm A1.txt
	rm A2.txt
	rm A3.txt
	rm A4.txt
	rm A5.txt
	rm A6.txt
	rm A7.txt
	rm A8.txt
	rm A9.txt

}

do_test(){

	# Do tests
	echo ''
	echo ''
	echo "## A single $1 file"

	echo ''
	echo " - 10 rounds of sed on a $1 file: "
	time for i in {1..10}; do
		cat "$1.file" | sed 's/<.*>//g' > /dev/null
	done 

	echo ''
	Echo " - 10 rounds of RexReplace on a $1 file: "
	time for i in {1..10}; do
		rexreplace '<.*>' '' "$1.file" -o > /dev/null
	done 

}


create_testdata

do_test '1Kb'
do_test '5Kb'
do_test '10Kb'
do_test '100Kb'
do_test '500Kb'
#do_test '1Mb'
#do_test '5Mb'
#do_test '10Mb'
#do_test '25Mb'
#do_test '50Mb'
#do_test '100Mb'



echo ''
echo ''
echo '----'
echo ''
echo ''
echo '## 10 files (10Kb each)'
cat 10Kb.file > A0.txt
cat A0.txt > A1.txt
cat A0.txt > A2.txt
cat A0.txt > A3.txt
cat A0.txt > A4.txt
cat A0.txt > A5.txt
cat A0.txt > A6.txt
cat A0.txt > A7.txt
cat A0.txt > A8.txt
cat A0.txt > A9.txt

echo ''
Echo " - sed on 10 files:	"
time for i in {1..10}; do
	cat A0.txt | sed 's/<.*>//g' > /dev/null
	cat A1.txt | sed 's/<.*>//g' > /dev/null
	cat A2.txt | sed 's/<.*>//g' > /dev/null
	cat A3.txt | sed 's/<.*>//g' > /dev/null
	cat A4.txt | sed 's/<.*>//g' > /dev/null
	cat A5.txt | sed 's/<.*>//g' > /dev/null
	cat A6.txt | sed 's/<.*>//g' > /dev/null
	cat A7.txt | sed 's/<.*>//g' > /dev/null
	cat A8.txt | sed 's/<.*>//g' > /dev/null
	cat A9.txt | sed 's/<.*>//g' > /dev/null
done 


echo ''
Echo " - RexReplace on 10 files:	"
time for i in {1..10}; do
	rexreplace '<.*>' '' -o A0.txt A1.txt A2.txt A3.txt A4.txt A5.txt A6.txt A7.txt A8.txt A9.txt > /dev/null
done 

echo ''
Echo " - RexReplace on 10 files given as one glob:"
time for i in {1..10}; do
	rexreplace '<.*>' '' -o A*.txt > /dev/null
done 


echo '----'

Echo "_All tests completed_."

remove_testdata


