#!/bin/bash

DATETIME=`date '+%Y-%m-%d %H:%M'`
RR_VERSION="v`rr -v`"
NODE_VERSION=`NODE -v`
echo ''
echo "# RexReplace vs \`sed\` speed test"
printf "\n\t%s\n\t%s\n\t%s\n\n" "$DATETIME" "RexReplace $RR_VERSION" "Node $NODE_VERSION"

echo "This test will remove HTML tags from the HTML sorce of George Orwell's 1984 to get the pure text version."

echo 'All testresults printed are the sum of 10 rounds given in seconds.'

TIMEFORMAT=%R

create_testdata(){
	#return # for debug

	curl -s 1984.surge.sh > source.file
	head -c $((1*1024))  source.file > 1Kb.file
	head -c $((5*1024))  source.file > 5Kb.file
	head -c $((10*1024)) source.file > 10Kb.file
	head -c $((100*1024)) source.file > 100Kb.file
	head -c $((500*1024)) source.file > 500Kb.file
	echo '' > 1Mb.file; for i in {1..2}; do cat 500Kb.file >> 1Mb.file; done
	echo '' > 5Mb.file; for i in {1..5}; do cat 1Mb.file >> 5Mb.file; done
	echo '' > 10Mb.file; for i in {1..10}; do cat 1Mb.file >> 10Mb.file; done
	echo '' > 25Mb.file; for i in {1..25}; do cat 1Mb.file >> 25Mb.file; done
	echo '' > 50Mb.file; for i in {1..50}; do cat 1Mb.file >> 50Mb.file; done
	echo '' > 100Mb.file; for i in {1..100}; do cat 1Mb.file >> 100Mb.file; done

	
}

remove_testdata(){
	#return # for debug

	rm source.file
	rm 1Kb.file
	rm 5Kb.file
	rm 10Kb.file
	rm 100Kb.file
	# rm 500Kb.file
	# rm 1Mb.file
	# rm 5Mb.file
	# rm 10Mb.file
	# rm 25Mb.file
	# rm 50Mb.file
	# rm 100Mb.file

	

}


run_rr(){

	echo ''
	printf " - RexReplace $2 on a %s file: \t" $1
	time for i in {1..100}; do
		$2 '<.*?>' '' "$1.file" -o > /dev/null
	done 
	echo ''

}



do_test(){

	# Do tests
	echo ''
	echo "## A single $1 file"
	echo ''

	echo '_100 rounds of:_'
	echo ''
	printf " - sed on %s file:          \t" $1
	time for i in {1..100}; do
		cat "$1.file" | sed 's/<.*?>//g' > /dev/null
	done 

	#run_rr $1 rr_3_m
#	run_rr $1 rr_5_m
	# run_rr $1 rr_6_m
	#run_rr $1 rr_6_b
	#run_rr $1 rr_6_b_u
	#run_rr $1 rr_6_c
	#run_rr $1 rr_6_c_js
	#run_rr $1 rr_6
	#run_rr $1 rr_6_b_c
#	run_rr $1 rr_6_b_c_js
	#run_rr $1 rr_6_b_u_c
	#run_rr $1 rr_6_b_u_c_js


# Total	1,977	98,141	94,509	95,242	96,773	95,887	95,728	97,053	94,747	94,314	95,418	96,743
# Compination	sed	rr_3_m	rr_5_m	rr_6_b	rr_6_b_u	rr_6_c	rr_6_c_js	rr_6	rr_6_b_c	rr_6_b_c_js	rr_6_b_u_c	rr_6_b_u_c_js
# 1kb	0,633	24,249	23,337	24,131	24,392	24,705	24,553	24,673	23,645	23,322	23,384	25,703
# 5kb	0,498	26,377	23,582	23,448	25,37	23,79	23,734	24,218	23,792	23,895	23,559	23,768
# 10kb	0,401	23,889	23,837	23,909	23,506	23,818	23,961	24,217	23,807	23,434	24,984	23,757
# 100kb	0,445	23,626	23,753	23,754	23,505	23,574	23,48	23,945	23,503	23,663	23,491	23,515


#	run_rr $1 rr_5_b
#	run_rr $1 rr_5_b_c_js


	run_rr $1 rr

}


create_testdata

do_test '1Kb'
do_test '5Kb'
do_test '10Kb'
do_test '100Kb'
 do_test '500Kb'
 do_test '1Mb'
 do_test '5Mb'
 do_test '10Mb'
 do_test '25Mb'
 do_test '50Mb'
 do_test '100Mb'




echo ''
echo '----'
echo ''
echo "_All tests completed_"

remove_testdata


