name: Auto publish

on: 
  push:
    branches:
    - master
    

jobs:
  build:
    if: ${{ 1==1 }}
    name: Autopublish dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Checking the who pushed
        run: |
          echo "The github.event.pusher is:"
          echo "${{ toJson(github.event.pusher) }}"
